services:
  - type: web
    name: laravel-docker-api
    env: docker
    repo: https://github.com/Aliou221/TON_REPO
    branch: main
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/database/database.sqlite
